# Generated by Django 5.0.6 on 2024-06-14 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sitedescription', models.TextField()),
                ('address1', models.CharField(default=' ', max_length=255)),
                ('address2', models.CharField(default=' ', max_length=255)),
                ('country', models.CharField(default=' ', max_length=100)),
                ('city', models.CharField(default=' ', max_length=255)),
                ('zipcode', models.CharField(default=' ', max_length=20)),
                ('sitelogo', models.ImageField(blank=True, upload_to='Site_logo/')),
                ('browsersitelogo', models.ImageField(blank=True, upload_to='Browser_tag_logo/')),
                ('primaryemail', models.EmailField(default=' ', max_length=254)),
                ('secondaryemail', models.EmailField(default=' ', max_length=254)),
                ('replaytoemail', models.EmailField(default=' ', max_length=254)),
                ('primarycontactnumber', models.CharField(default=' ', max_length=20)),
                ('secondarycontactnumber', models.CharField(default=' ', max_length=20)),
                ('tertiarycontactnumber', models.CharField(default=' ', max_length=20)),
                ('facebookurl', models.CharField(default=' ', max_length=255)),
                ('twitterurl', models.CharField(default=' ', max_length=255)),
                ('instagramurl', models.CharField(default=' ', max_length=255)),
                ('skypeurl', models.CharField(default=' ', max_length=255)),
                ('linkedinurl', models.CharField(default=' ', max_length=255)),
                ('metakeywords', models.CharField(default=' ', max_length=255)),
                ('metadescription', models.CharField(default=' ', max_length=50000)),
                ('googleanalyticscode', models.CharField(default=' ', max_length=50000)),
                ('cssinput', models.CharField(default=' ', max_length=255)),
                ('jsinput', models.CharField(default=' ', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='package_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_destination', models.CharField(max_length=100)),
                ('to_destination', models.CharField(max_length=100)),
                ('check_date', models.DateField()),
                ('duration', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Travel Packages',
            },
        ),
        migrations.CreateModel(
            name='AddPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('rate', models.CharField(default='0', max_length=10)),
                ('days', models.IntegerField(default=0)),
                ('nights', models.IntegerField(default=0)),
                ('people', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='Package_Images/')),
                ('condition1', models.CharField(default='', max_length=1000)),
                ('condition2', models.CharField(default='', max_length=1000)),
                ('condition3', models.CharField(default='', max_length=1000)),
                ('condition4', models.CharField(default='', max_length=1000)),
                ('condition5', models.CharField(default='', max_length=1000)),
                ('famous_place', models.CharField(default='', max_length=1000)),
                ('city_visit', models.CharField(default='', max_length=1000)),
                ('rooms', models.CharField(default='', max_length=1000)),
                ('food', models.CharField(default='', max_length=1000)),
                ('image_caption', models.CharField(default='', max_length=1000)),
                ('image_description', models.CharField(default='', max_length=1000)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image1', models.ManyToManyField(related_name='package_gallery', to='WinskyApp.image')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WinskyApp.package')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('add_package', models.ManyToManyField(to='WinskyApp.addpackage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
